### ISSUE TITLE
Sould I add another Kdrama Quiz page?

### ISSUE THREAD

**Issue by Rishika10442** [SimranS22/K-Quiz#2]

**Comment by SimranS22** [comment]
Sure.

You will have to add a js file(with new questions of the drama), css file, drama_name.html file and make necessary changes like add an extra segment in the index.html file. Please provide screenshots of the altered webpage when making the pull request so that I can see what changes have been made. The other js files have the template of question. You would just have to alter. If you planning to add more sections. Send screenshots of those too.

Good luck!!
